apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # Optional, if using internal load balancer
spec:
  type: LoadBalancer
  loadBalancerIP: 85.210.112.215
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: nginx-ingress
