---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  serviceName: "mysql-db"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: db
          image: mrepo.azurecr.io/db:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: springbootdb
            - name: MYSQL_USER
              value: opstree
            - name: MYSQL_PASSWORD
              value: opstree123
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      imagePullSecrets:
        - name: msecret
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-db
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
  labels:
    app: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: mymvn
          image: mrepo.azurecr.io/mymvn:v1
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: mysql-db
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: opstree
            - name: DB_PASSWORD
              value: opstree123
            - name: DB_NAME
              value: springbootdb
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
      imagePullSecrets:
        - name: msecret

---
apiVersion: v1
kind: Service
metadata:
  name: maven-app
  labels:
    app: maven-app
spec:
  type: NodePort
  selector:
    app: maven-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
