name: Maven and DB CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Maven project
        run: mvn -B package --file pom.xml

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: mrepo.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Maven Docker image
        run: |
          docker build . -t mrepo.azurecr.io/maven:v1
          docker push mrepo.azurecr.io/maven:v1

      - name: Build and push DB Docker image
        run: |
          docker build -f Dockerfile -t mrepo.azurecr.io/db:v2 Dockerfile
          docker push mrepo.azurecr.io/db:v2

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensure build-and-push job completes successfully before starting deploy-to-aks job

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group m --name Gcluster

      - name: Update Maven deployment in AKS
        run: |
          kubectl set image deployment/maven-deployment maven=mrepo.azurecr.io/maven:v1

      - name: Update DB deployment in AKS
        run: |
          kubectl set image deployment/db-deployment db=mrepo.azurecr.io/db:v2
