name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: <your-acr-name>.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . -t <your-acr-name>.azurecr.io/my-java-app:${{ github.sha }}
          docker push <your-acr-name>.azurecr.io/my-java-app:${{ github.sha }}

  cd:
    runs-on: ubuntu-latest
    needs: ci  # Ensure CI job completes successfully before starting CD job

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group <your-resource-group> --name <your-aks-cluster>

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/<your-deployment-name> <container-name>=<your-acr-name>.azurecr.io/my-java-app:${{ github.sha }}

